---
name: Federal Front Door - Information Exchange Alpha
full_name: ffd-info-exchange
type: app
owner_type: project
status: active
stage: alpha
testable: true
description: >
  @kategarklavs to populate
impact: >
  @kategarklavs to populate
stack:
- Django
licenses:
  .about.yml:
    name: CC0
    url: https://github.com/18F/about_yml/blob/master/LICENSE.md
tasks: https://github.com/18F/ffd-info-exchange/issues#boards
contact:
- url: mailto:michael.antiporta@gsa.gov #replace once we have a google group
  text: Porta Antiporta #replace once we have a google group
team:
- github: 18F/ffd-info-x
  role: team