# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(help_text='Your first name', max_length=250)),
                ('name_last', models.CharField(help_text='Your last name', max_length=250)),
                ('date_of_birth', models.DateTimeField(help_text='Your date of birth (MM/DD/YYYY)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
